### ISSUE TITLE
你好，请问能将后端代码一并开源吗，感谢！

### ISSUE THREAD

**Issue by liskarmw** [NiallLDY/ARLibrary#1]
最近在学习该项目，发现有很多涉及到服务端请求部分，看的不是很明白，也无法运行，所以希望能一并开源服务端的代码（看起来用的应该是 Tomcat）。十分感谢！

**Comment by NiallLDY** [comment]
> 最近在学习该项目，发现有很多涉及到服务端请求部分，看的不是很明白，也无法运行，所以希望能一并开源服务端的代码（看起来用的应该是 Tomcat）。十分感谢！

后端得找 @Zouhaonan123 要，我没有完整的代码

**Comment by liskarmw** [comment]
好的感谢！

**Comment by liskarmw** [comment]
好像 @Zouhaonan123 已经不怎么活跃在 GitHub 了，请问大佬你可以帮我联系一下嘛，真的非常感谢！！！（有偿，可以加我微信）
以下是我的联系方式：
- 邮箱：liskarmw@qq.com
- 微信：liskarmw

**Comment by NiallLDY** [comment]
我建议你把项目中的后端部分删除就可以了，导航部分所需的内容都在项目中，例如预置的[图书信息](https://github.com/NiallLDY/ARLibrary/blob/master/ARLibrary/books.json)、图书[封面](https://github.com/NiallLDY/ARLibrary/tree/master/ARLibrary/Assets.xcassets/AR%20Resources.arresourcegroup)。你可以改成本地直接读取。
后端涉及到的其它内容为用户信息、用户登陆、收藏等。是导航非必要的内容，你可以自己搭建相应的数据库并编写后端代码。

**Comment by liskarmw** [comment]
好的，我努力尝试，感谢你花时间！
